name: Create Release

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    build:
        name: Create release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              name: Create Release
              run: gh release create "${GITHUB_REF#refs/*/}" -t "$(grep name config/version.php | awk -F "'" '{print $4}')" --notes-file RELEASE_NOTES.md
