packaging-trigger:
  stage: packaging-trigger
  variables:
    PACKAGING_TRIGGER_BRANCH: "main"
    DOWNSTREAM_PROJECT_ID: "$PACKAGING_PROJECT_ID"
  image: debian:bullseye-slim
  script:
    - apt update && apt install -y curl
    - bash .gitlab-ci/scripts/bin/packaging-trigger.sh "$CI_COMMIT_TAG" "$PACKAGING_TRIGGER_BRANCH"
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
