release_notes:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  release:
    description: './RELEASE_NOTES.md'
    tag_name: $CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
      when: on_success
  script: echo "Creating relase notes for $CI_COMMIT_TAG"
  stage: release

release_notes_candidate:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  release:
    tag_name: $CI_COMMIT_TAG
    description: $CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$/'
      when: on_success
  script: echo "Creating relase notes for $CI_COMMIT_TAG"
  stage: release
